[package]
name = "editsc"
version = "0.1.0"
edition = "2018"

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.68"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = "0.4.5"
bytes = "0.5.6"

[lib]
crate-type = ["cdylib", "rlib"]
